#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "vex_competition_include.c"

void moveForward(int speed){
	setMotor(port2, -1 * speed);
	setMotor(port3, speed);
	forward(speed);
	stopMotor(port2);
	stopMotor(port3);
}

void moveBackward(int speed){
	setMotor(port2, -1 * speed);
	setMotor(port3, speed);
	forward(-1 * speed);
	stopMotor(port2);
	stopMotor(port3);
}
void right(int speed){
	setMotor(port2, speed);
	forward(speed);
	stopMotor(port2);
}

void left(int speed){
	setMotor(port3, -1 * speed);
	forward(-1 * speed);
	stopMotor(port3);
}

void lift(int speed){
	setMotor(port4, speed);
	forward(speed);
	stopMotor(port4);
}

// open claw
void open(){
	setMotor(port6, 127);
	wait(1.5);
	stopMotor(port6);
}

// close claw
void close(){
	setMotor(port6, -127);
	wait(1.5);
	stopMotor(port6);
}

task main(){
	// port2 and port3 are for the motors
	// port4 is to lift the claw
	// port5 is to open and close the claw
	int isForward = 1;
	int speed = 10;
	while(1==1){
		if(vexRT[Btn8U] == 1){
			moveForward(speed);
			if(speed <= 127){
				speed += 1;}
			}

  	if(vexRT[Btn6D] == 1){
			stopAllMotors();
			speed = 10;
			}

		if(vexRT[Btn8D] == 1){
			moveBackward(-1 * speed);
			if(speed <= 127){
				speed += 1;
			}
		}
		if(vexRT[Btn8L] == 1){
			left(-127);
		}
		if(vexRT[Btn8R] == 1){
			right(-127);
		}
		if(vexRT[Btn5U] == 1){
			lift(-66);
		}
		if(vexRT[Btn5D] == 1){
			lift(66);
		}
		if(vexRT[Btn7U] == 1){
			open();
		}
		if(vexRT[Btn7D] == 1){
			close();
		}

	}
}
